# Ch. 6 Exercises

**My Comments:** Chapter 6 exercises were relatively straight-forward for me. Was unsure if 6.6 wanted an input of a list of strings or a sentence string, so I just made a function that accepted a string. For that problem, I also made everything lower case to ignore "casing" of letters.

## 6.2 What's Wrong with This Code?

In [1]:
from collections import Counter
text = ('to be or not to be that is the question')
counter = Counter(text.split())
for word, count in sorted(counter):
    print(f'{word:<12}{count}')

b           e
i           s


ValueError: too many values to unpack (expected 2)

**My Answer:** The problem here is the for loop didn't loop over counter.items(), which allows unpacking to the word and count variables.

Below is what the correct code would look like:

In [6]:
from collections import Counter
text = ('to be or not to be that is the question')
counter = Counter(text.split())
for word, count in sorted(counter.items()):
    print(f'{word:<12}{count}')

be          2
is          1
not         1
or          1
question    1
that        1
the         1
to          2


## 6.3 What Does This Code Do?

In [7]:
temperatures = {
    'Monday': [66, 70, 74],
    'Tuesday': [50, 56, 64],
    'Wednesday': [75, 80, 83],
    'Thursday': [67, 74, 81]
}

for k, v in temperatures.items():
    print(f'{k}: {sum(v)/len(v):.2f}')

Monday: 70.00
Tuesday: 56.67
Wednesday: 79.33
Thursday: 74.00


**Answer:** This piece of code takes the average temperatures of all the days (keys) in the temperatures dictionary and prints them out.

This is done by summing all the values in each list for each day, and dividing it by the length of each list.

## 6.6 Data Science: Duplicate Word Removal

Write a function that receives a list of words, then determines and displays in alphabetical order only the unique words. Treat uppercase and lowercase letters the same. The function should use a set to get the unique words in the list. Test your function with several sentences.

In [20]:
def unique_sorted_sentence(sentence):
    """Accepts a sentence or list of words and returns only the unique words in alphabetical order."""
    unique_words = {word.lower() for word in sentence} # make each word lower case and remove dupes
    return sorted(unique_words)

In [21]:
print(unique_sorted_sentence(['The', 'cat', 'jumped', 'over', 'the', 'wall', 'and', 'then', 'the', 'cat', 'ran', 'home']))

['and', 'cat', 'home', 'jumped', 'over', 'ran', 'the', 'then', 'wall']


In [22]:
print(unique_sorted_sentence(['I', 'am', 'Chris', 'and', 'I', 'am', 'a', 'UCLA', 'MSBA', 'student']))

['a', 'am', 'and', 'chris', 'i', 'msba', 'student', 'ucla']


## 6.9 Dictionary Manipulations

Using the following dictionary, which maps country names to Internet top-level domains (TLDs):

```python
tlds = {'Canada': 'ca', 'United States': 'us', 'Mexico': 'mx'}
```

***a) Check whether the dictionary contains the key 'Canada'.***

In [34]:
tlds = {'Canada': 'ca', 'United States': 'us', 'Mexico': 'mx'}

'Canada' in tlds

True

***b) Check whether the dictionary contains the key 'France'.***

In [35]:
'France' in tlds

False

***c) Iterate through the key-value pairs and display them in two-column format***

In [37]:
for name, abbrev in tlds.items():
    print(f'{name:<20}{abbrev}')

Canada              ca
United States       us
Mexico              mx


***d) Add the key-value pair 'Sweden' and 'sw' (which is incorrect)***

In [38]:
tlds['Sweden'] = 'sw'

In [39]:
tlds

{'Canada': 'ca', 'United States': 'us', 'Mexico': 'mx', 'Sweden': 'sw'}

***e) Update the value for the key 'Sweden' to 'se'***

In [40]:
tlds['Sweden'] = 'se'

In [41]:
tlds

{'Canada': 'ca', 'United States': 'us', 'Mexico': 'mx', 'Sweden': 'se'}

***f) Use a dictionary comprehension to reverse the keys and values***

In [43]:
reverse = {value: key for key, value in tlds.items()}

In [44]:
reverse

{'ca': 'Canada', 'us': 'United States', 'mx': 'Mexico', 'se': 'Sweden'}

***g) With the result of part (f), use a dictionary comprehension to convert the country names to all uppercase letters.***

In [49]:
upper = {key: value.upper() for key, value in reverse.items()}

In [50]:
upper

{'ca': 'CANADA', 'us': 'UNITED STATES', 'mx': 'MEXICO', 'se': 'SWEDEN'}

---

# Ch. 7 Exercises

**My Comments:** numpy for the most part was easy to understand. The hstack and vstack functions took a little more time to understand/visualize, but I think I understand it now.

## 7.2 Broadcasting

Use arange to create a 2-by-2 array containing the numbers 0-3. Use broadcasting to perform each of the following operations on the original array:

***a) Cube every element of the array.***

In [59]:
import numpy as np

my_array = np.arange(0, 4).reshape(2, 2)

my_array

array([[0, 1],
       [2, 3]])

In [57]:
my_array ** 3

array([[ 0,  1],
       [ 8, 27]])

***b) Add 7 to every element of the array.***

In [58]:
my_array + 7

array([[ 7,  8],
       [ 9, 10]])

***c) Multiply every element of the array by 2.***

In [60]:
my_array * 2

array([[0, 2],
       [4, 6]])

## 7.3 Element-Wise array Multiplication

Create a 3-by-3 array containing the even integers from 2 through 18. Create a second 3-by-3 array containing the integers from 9 down to 1, then multiply the first array  by the second.

In [66]:
import numpy as np #not necessary, but putting it here to show numpy is going to be used

even_array = np.arange(2, 19, 2).reshape(3, 3)

even_array

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [63]:
desc_array = np.arange(9, 0, -1).reshape(3, 3)

desc_array

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [64]:
even_array * desc_array

array([[18, 32, 42],
       [48, 50, 48],
       [42, 32, 18]])

## 7.9 Data Science: Indexing and Slicing arrays

Create an array containing the values 1-15, reshape it into a 3-by-5 array, then use indexing and slicing techniques to perform each of the following operations:

***a) Select row 2.***

In [2]:
import numpy as np #not necessary, but putting it here to show numpy is going to be used

test_array = np.arange(1, 16).reshape(3, 5)

test_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [4]:
print(f'Row 2:\n{test_array[1]}')

Row 2:
[ 6  7  8  9 10]


***b) Select column 4.***

In [5]:
print(f'Column 4:\n{test_array[:, 4]}'

Column 4:
[ 5 10 15]


***c) Select rows 0 and 1.***

In [6]:
print(f'Rows 0 and 1:\n{test_array[0:2]}')

Rows 0 and 1:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


***d) Select columns 2-4.***

In [7]:
print(f'Columns 2 and 4:\n{test_array[:, 2:5]}')

Columns 2 and 4:
[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


***e) Select the element that is in row 1 and column 4.***

In [9]:
print(f'Element in row 1, column 4: {test_array[1, 4]}')

Element in row 1, column 4: 10


***f) Select all elements from rows 1 and 2 that are in columns 0, 2 and 4.***

In [10]:
print(f'Elements in rows 1 and 2 and columns 0, 2, and 4:\n{test_array[1:3, [0, 2, 4]]}')

Elements in rows 1 and 2 and columns 0, 2, and 4:
[[ 6  8 10]
 [11 13 15]]


## 7.14 Data Science: Horizontal and Vertical Stacking

Create the two-dimensional arrays

```python
array1 = np.array([[0, 1], [2, 3]])
array2 = np.array([[4, 5], [6, 7]])
```

In [80]:
array1 = np.array([[0, 1], [2, 3]])
array2 = np.array([[4, 5], [6, 7]])

***a) Use vertical stacking to create the 4-by-2 array named array3 with array1 stacked on top of array2.***

In [87]:
array3 = np.vstack((array1, array2))

In [88]:
array3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

***b) Use horizontal stacking to create the 2-by-4 array named array 4 with array2 to the right of array1.***

In [89]:
array4 = np.hstack((array1, array2))

array4

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

***c) Use vertical stacking with two copies of array4 to create a 4-by-4 array5.***

In [91]:
array5 = np.vstack((array4, array4))

array5

array([[0, 1, 4, 5],
       [2, 3, 6, 7],
       [0, 1, 4, 5],
       [2, 3, 6, 7]])

***d) Use horizontal stacking with two coppies of array3 to create a 4-by-4 array6.***

In [92]:
array6 = np.hstack((array3, array3))

array6

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5],
       [6, 7, 6, 7]])